#!/usr/bin/env bash
#using dig to display information
#also printing out detials of th dig in a particular format


domain_check() {
	arg1=$1
	arg2=$2
	arg3=$3
	query = $(dig "arg2"."arg$1" | grep -A1 'ANSWER SECTION' | tr '\t' '\n' | tail -n 2 | tr '\n' ' ')
	echo "arg2 $query" | awk '{print "The subdomain " arg1 " is a " arg2 " record and points to " arg3}'
}


if ["$#" -eq 1 ]; then
	domain_check "arg1" "www"
	domain_check "arg1" "lb-01"
	domain_check "arg1" "web-01"
	domain_check "arg1" "web-02"
elif [ "$#" -eq 2 ]; then
	dns_config "arg1" "arg2"
fi

