#!/usr/bin/env bash
#using dig to display information
#also printing out detials of th dig in a particular format


domain_check() {
	arg1=$1
	arg2=$2
	query=$(dig "$arg2"."$arg1" | grep -A1 'ANSWER SECTION' | tr '\t' '\n' | tail -n 2 | tr '\n' ' ')
	echo "$arg2 $query" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}


if [ "$#" -eq 1 ]; then
	domain_check "$1" "www"
	domain_check "$1" "lb-01"
	domain_check "$1" "web-01"
	domain_check "$1" "web-02"
elif [ "$#" -eq 2 ]; then
	domain_check "$1" "$2"
fi

