#!/usr/bin/env bash
#this script takes 4 paramters to transfer file to a server from a client

if [ "$#" -lt 3 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
elif [ $# -eq 4 ]; then
    scp -i "$4" -o 'StrictHostKeyChecking=no' "$1" "$3@$2":./
fi
