#!/usr/bin/env bash
#this configures Nginx so that /redirect_me is redirecting to anoter page

sudo apt-get -y install nginx
sudo service nginx start
ufw
sudo sed -i '37i\rewrite ^/redirect_me http://abdullateef-tech permanent;'  /etc/ninx/sites-available/default
sudo service nginx restart