#!/usr/bin/env bash
#ngix configuration file that adda a custom header

sudo apt-get -y update
sudo apt-get -y install nginx
sudo sed -i "60i add_header X-Served-By \$hostname;" /etc/nginx/nginx.conf
sudo service nginx restart
