#!/usr/bin/env bash
#A bash script tat prints it s own PID

trap "rm -rf /var/run/myscript.pid; exit" SIGQUIT
trap "echo 'Y U nolove me?!'" SIGINT
trap "echo 'I hate the kill command'; rm -rf /var/run/myscript.pid; exit" SIGQUIT

echo $$ > /var/run/myscript.pid
while true
do
	echo "To infinity and beyond"
	sleep 2
done
