#!/usr/bin/env bash
#This script lists all the second field pf the curent dorectory

f="school"
if [ -e $f ]
then
	echo "$f file esits"
	if [ -s "school" ]
	then
		echo "$f file is not empty"
	else
		echo "$f file is empty"
	fi

	if [ -f $f ]
	then
		echo "$f is a regular file"
	fi
else
	echo "$f file does not exist"
fi
