#!/usr/bin/env bash
#this script uses switches to nginx instead of roor ad a user to
pkill apache2
sudo chown -R nginx /etc/nginx/
sudo sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sudo chmod 644 /etc/nginx/nginx.conf
sudo -u nginx service nginx restart

